### ISSUE TITLE
AndroidEnv does not work in WSL

### ISSUE THREAD

**Issue by psurya1994** [deepmind/android_env#14]
I've setup android studio on windows and am trying to load the environment from [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I have `got an unexpected keyword argument 'use_poll'` error while trying to load the environment. Any ideas on how I can fix this? 

Full error:
```
>>> import android_env
>>> env = android_env.load(avd_name='Pixel_2_API_30', android_avd_home='/mnt/c/Users/Surya Penmetsa/.android/avd/Pixel_2_API_30.avd', android_sdk_root='/mnt/c/Users/Surya Penmetsa/AppData/Local/Android/Sdk', emulator_path='/mnt/c/Users/Surya Penmetsa/AppData/Local/Android/Sdk/emulator/emulator.exe', adb_path='/mnt/c/Users/Surya Penmetsa/AppData/Local/Android/Sdk/platform-tools/adb.exe', task_path='downloads/classic_2048.textproto')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/loader.py", line 73, in load
    coordinator = coordinator_lib.Coordinator(simulator, task_manager)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/coordinator.py", line 88, in __init__
    self._restart_simulator()
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/coordinator.py", line 181, in _restart_simulator
    self._simulator.launch()
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/base_simulator.py", line 136, in launch
    self._post_launch_setup()
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/emulator_simulator.py", line 117, in _post_launch_setup
    super()._post_launch_setup()
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/base_simulator.py", line 151, in _post_launch_setup
    self._adb_controller.get_screen_dimensions())
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 459, in get_screen_dimensions
    self._wait_for_device(timeout=timeout)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 234, in _wait_for_device
    ready = self._check_device_is_ready(timeout=timeout)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 247, in _check_device_is_ready
    ['shell', 'service', 'check', service], timeout=timeout)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 116, in _execute_command
    adb_output = self._execute_shell_command(args[1:], timeout=timeout)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 149, in _execute_shell_command
    self._init_shell(timeout=timeout)
  File "/home/surya/anaconda3/lib/python3.6/site-packages/android_env/components/adb_controller.py", line 191, in _init_shell
    self._adb_shell = pexpect.spawn(command, use_poll=True, timeout=timeout)
TypeError: __init__() got an unexpected keyword argument 'use_poll'
```

**Comment by kenjitoyama** [comment]
Hello @psurya1994, we have never tried running AndroidEnv on Windows, so thanks for the report.

From the error message, it looks like it's a limitation in one of the libraries we use, `pexpect`, which does not offer `popen.spawn` on Windows. According to their [docs](https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows), we can try to see if we can use `PopenSpawn` but it would be better if you can try it in your local machine and report back to us since we don't have Windows machines to try.

Let me know what you think,

Thanks!

**Comment by psurya1994** [comment]
Thank you @kenjitoyama! That makes sense.

I'll let this pass, for now. So closing the issue. If someone else faces the same problem, they can reopen.

**Comment by kenjitoyama** [comment]
Hello @psurya1994, it's ok to leave it open. We are also planning to use a different communication mechanism (gRPC) which could help here and remove the need for this particular `pexpect` call. Eventually we do want to support running on Windows via WSL.
Tagging @a-gergely who's been experimenting with gRPC.

Thanks,

Daniel

**Comment by a-gergely** [comment]
We've now made some modifications to make AndroidEnv compatible with Windows (credits to @yizhangliu for parts of this). I'm closing the issue, but please let us know if there are any problems.

**Comment by yizhangliu** [comment]
> 
> 
> We've now made some modifications to make AndroidEnv compatible with Windows (credits to @yizhangliu for parts of this). I'm closing the issue, but please let us know if there are any problems.

Thanks to you.    Only one problem:
        E0728 14:53:42.749846 12156 adb_controller.py:152] Failed to execute ADB command ['C:/Users/ThinkPad/AppData/Local/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-24469', 'shell', 'pm', 'grant', 'com.dozingcatsoftware.bouncy', 'android.permission.ACCESS_COARSE_LOCATION']
        I run 'adb -P 5037 -s emulator-5554 shell pm grant com.dozingcatsoftware.bouncy android.permission.ACCESS_COARSE_LOCATION' ,   got this result: 
        'Security exception: Package com.dozingcatsoftware.bouncy has not requested permission android.permission.ACCESS_COARSE_LOCATION'
        So, I skip  'grant_permissions',   then  everything is ok.
